"""Initial migration.

Revision ID: 11450887b3f1
Revises: 
Create Date: 2024-10-23 21:02:13.073602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11450887b3f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
