"""empty message

Revision ID: 35f0f2a5e434
Revises: aa80c052601f
Create Date: 2024-10-29 16:11:16.196172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f0f2a5e434'
down_revision = 'aa80c052601f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
