"""schema update

Revision ID: 3eb66168a514
Revises: 11450887b3f1
Create Date: 2024-10-27 07:23:15.519352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb66168a514'
down_revision = '11450887b3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
