"""empty message

Revision ID: a5cd4d5a3c0d
Revises: 35f0f2a5e434
Create Date: 2024-11-07 18:33:03.047119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cd4d5a3c0d'
down_revision = '35f0f2a5e434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dorm_block', sa.String(length=80), nullable=False))
        batch_op.drop_column('apt_block')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apt_block', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('dorm_block')

    # ### end Alembic commands ###
