"""empty message

Revision ID: aa80c052601f
Revises: c1bd418fdf71
Create Date: 2024-10-27 21:25:30.183784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa80c052601f'
down_revision = 'c1bd418fdf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
