"""user schema update

Revision ID: c1bd418fdf71
Revises: 3eb66168a514
Create Date: 2024-10-27 18:32:33.738909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bd418fdf71'
down_revision = '3eb66168a514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
